CC=gcc
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=node.c project2.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=project2

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@


